lang: ja
layout: page

title: Ocala ドキュメント
description: Ocala のドキュメントサイトです。
github_username:  maokij

theme: minima
plugins:
  - jekyll-feed

markdown: GFM

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
